apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy
spec:
  selector:
    matchLabels:
      app: myweb
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb 
        image: 873563726923.dkr.ecr.ap-northeast-2.amazonaws.com/tea4testecr:85
        ports:
          - containerPort: 80

        

---

apiVersion: v1
kind: Service
metadata:
  name: myweb
  labels:
    app: myweb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: myweb
