apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- deployment.yaml
resources:
- ../base
images:
- name: user-api-image
  newName: 873563726923.dkr.ecr.ap-northeast-2.amazonaws.com/tea4testecr
  newTag: "<new tag>"
